Global message: '&4Its ''%p''s birthday today!'
Birthday Message: '&eHappy Birthday! Here is a gift!'
Message interval: 0
Iconomy Money: 0
Number of gifts: '1'
Timed message: '&4Wish a happy birthday to: %p'
Use american date format: 1
Month mode: 0
Items on birthday: '92'