package me.fun.woder.BirthDay;

import java.util.HashMap;

import me.fun.woder.BirthDay.BirthDay;

public class ItemList {
public static BirthDay plugin;
public static HashMap<String, String> ID = new HashMap<String, String>();
	
	public ItemList(BirthDay instance) {
	  plugin = instance;
	}
	
	public static void Call(){
		  ItemList.ID.put("1", "Stone");
		  ItemList.ID.put("2", "Grass");
		  ItemList.ID.put("3", "Dirt");
		  ItemList.ID.put("4", "Cobblestone");
		  ItemList.ID.put("5", "Wooden Plank");
		  ItemList.ID.put("6", "Sapling");
		  ItemList.ID.put("6:1", "Sapling (Pine)");
		  ItemList.ID.put("6:2", "Sapling (Birch)");
		  ItemList.ID.put("7", "Bedrock");
		  ItemList.ID.put("8", "Water (Still)");
		  ItemList.ID.put("9", "Water");
		  ItemList.ID.put("10", "Lava (Still)");
		  ItemList.ID.put("11", "Lava");
		  ItemList.ID.put("12", "Sand");
		  ItemList.ID.put("13", "Gravel");
		  ItemList.ID.put("14", "Gold Ore");
		  ItemList.ID.put("15", "Iron Ore");
		  ItemList.ID.put("16", "Coal Ore");
		  ItemList.ID.put("17", "Wood");
		  ItemList.ID.put("17:1", "Wood (Pine)");
		  ItemList.ID.put("17:2", "Wood (Birch)");
		  ItemList.ID.put("18", "Leaves");
		  ItemList.ID.put("18:1", "Leaves (Pine)");
		  ItemList.ID.put("18:2", "Leaves (Birch)");
		  ItemList.ID.put("19", "Sponge");
		  ItemList.ID.put("20", "Glass");
		  ItemList.ID.put("21", "Lapis Lazuli Ore");
		  ItemList.ID.put("22", "Lapis Lazuli Block");
		  ItemList.ID.put("23", "Dispenser");
		  ItemList.ID.put("24", "Sandstone");
		  ItemList.ID.put("25", "Note Block");
		  ItemList.ID.put("26", "Bed (Block)");
		  ItemList.ID.put("27", "Powered Rail");
		  ItemList.ID.put("28", "Detector Rail");
		  ItemList.ID.put("29", "Sticky Piston");
		  ItemList.ID.put("30", "Web");
		  ItemList.ID.put("31", "Tall Grass (Dead Shrub)");
		  ItemList.ID.put("31:1", "Tall Grass");
		  ItemList.ID.put("31:2", "Tall Grass (Fern)");
		  ItemList.ID.put("32", "Dead Shrub");
		  ItemList.ID.put("33", "Piston");
		  ItemList.ID.put("34", "Piston (Head)"); //Why the hell would someone give this as a gift??
		  ItemList.ID.put("35", "Wool");
		  ItemList.ID.put("35:1", "Orange Wool");
		  ItemList.ID.put("35:2", "Magenta Wool");
		  ItemList.ID.put("35:3", "Light Blue Wool");
		  ItemList.ID.put("35:4", "Yellow Wool");
		  ItemList.ID.put("35:5", "Lime Wool");
		  ItemList.ID.put("35:6", "Pink Wool");
		  ItemList.ID.put("35:7", "Gray Wool");
		  ItemList.ID.put("35:8", "Light Gray Wool");
		  ItemList.ID.put("35:9", "Cyan Wool");
		  ItemList.ID.put("35:10", "Purple Wool");
		  ItemList.ID.put("35:11", "Blue Wool");
		  ItemList.ID.put("35:12", "Brown Wool");
		  ItemList.ID.put("35:13", "Green Wool");
		  ItemList.ID.put("35:14", "Red Wool");
		  ItemList.ID.put("35:15", "Black Wool");
		  ItemList.ID.put("37", "Dandelion");
		  ItemList.ID.put("38", "Rose");
		  ItemList.ID.put("39", "Brown Mushroom");
		  ItemList.ID.put("40", "Red Mushroom");
		  ItemList.ID.put("41", "Block of Gold");
		  ItemList.ID.put("42", "Block of Iron");
		  ItemList.ID.put("43", "Stone Slab (Double)");
		  ItemList.ID.put("43:1", "Sandstone Slab (Double)");
		  ItemList.ID.put("43:2", "Wooden Slab (Double)");
		  ItemList.ID.put("43:3", "Cobblestone Slab (Double)");
		  ItemList.ID.put("43:4", "Brick Slab (Double)");
		  ItemList.ID.put("43:5", "Stone Brick Slab (Double)");
		  ItemList.ID.put("44", "Stone Slab");
		  ItemList.ID.put("44:1", "Sandstone Slab");
		  ItemList.ID.put("44:2", "Wooden Slab");
		  ItemList.ID.put("44:3", "Cobblestone Slab");
		  ItemList.ID.put("44:4", "Brick Slab");
		  ItemList.ID.put("44:5", "Stone Brick Slab");
		  ItemList.ID.put("45", "Brick");
		  ItemList.ID.put("46", "TNT");
		  ItemList.ID.put("47", "Bookcase");
		  ItemList.ID.put("48", "Moss Stone");
		  ItemList.ID.put("49", "Obsidian");
		  ItemList.ID.put("50", "Torch");
		  ItemList.ID.put("51", "Fire");
		  ItemList.ID.put("52", "Mob Spawner");
		  ItemList.ID.put("53", "Wooden Stairs");
		  ItemList.ID.put("54", "Chest");
		  ItemList.ID.put("55", "Redstone Wire");
		  ItemList.ID.put("56", "Diamond Ore");
		  ItemList.ID.put("57", "Block of Diamond");
		  ItemList.ID.put("58", "Workbench");
		  ItemList.ID.put("59", "Wheat (Crop)");
		  ItemList.ID.put("60", "Farmland"); //Why would you give this to someone...
		  ItemList.ID.put("61", "Furnace");
		  ItemList.ID.put("62", "Furnace (Smelting)"); //Once again...why..
		  ItemList.ID.put("63", "Sign (Block)");
		  ItemList.ID.put("64", "Wood Door (Block)");
		  ItemList.ID.put("65", "Ladder");
		  ItemList.ID.put("66", "Rails");
		  ItemList.ID.put("67", "Cobblestone Stairs");
		  ItemList.ID.put("68", "Sign (Wall Block)");
		  ItemList.ID.put("69", "Lever");
		  ItemList.ID.put("70", "Stone Pressure Plate");
		  ItemList.ID.put("71", "Iron Door (Block)");
		  ItemList.ID.put("72", "Wooden Pressure Plate");
		  ItemList.ID.put("73", "Redstone Ore");
		  ItemList.ID.put("74", "Redstone Ore (Glowing)"); //Little strange for a gift, no?
		  ItemList.ID.put("75", "Redstone Torch (Off)");
		  ItemList.ID.put("76", "Redstone Torch");
		  ItemList.ID.put("77", "Stone Button");
		  ItemList.ID.put("78", "Snow");
		  ItemList.ID.put("79", "Ice");
		  ItemList.ID.put("80", "Snow Block");
		  ItemList.ID.put("81", "Cactus");
		  ItemList.ID.put("82", "Clay Block");
		  ItemList.ID.put("83", "Sugar Cane (Block)");
		  ItemList.ID.put("84", "Jukebox");
		  ItemList.ID.put("85", "Fence");
		  ItemList.ID.put("86", "Pumpkin");
		  ItemList.ID.put("87", "Netherrack");
		  ItemList.ID.put("88", "Soul Sand");
		  ItemList.ID.put("89", "Glowstone");
		  ItemList.ID.put("90", "Portal");
		  ItemList.ID.put("91", "Jack-O-Lantern");
		  ItemList.ID.put("92", "Cake (Block)");
		  ItemList.ID.put("93", "Redstone Repeater (Block Off)");
		  ItemList.ID.put("94", "Redstone Repeater (Block On)");
		  ItemList.ID.put("95", "Locked Chest");
		  ItemList.ID.put("96", "Trapdoor");
		  ItemList.ID.put("97", "Silverfish Stone");
		  ItemList.ID.put("98", "Stone Bricks");
		  ItemList.ID.put("98:1", "Mossy Stone Bricks");
		  ItemList.ID.put("98:2", "Cracked Stone Bricks");
		  ItemList.ID.put("99", "Brown Mushroom (Block)");
		  ItemList.ID.put("100", "Red Mushroom (Block)");
		  ItemList.ID.put("101", "Iron Bars");
		  ItemList.ID.put("102", "Glass Pane");
		  ItemList.ID.put("103", "Melon (Block)");
		  ItemList.ID.put("104", "Pumpkin Vine");
		  ItemList.ID.put("105", "Melon Vine");
		  ItemList.ID.put("106", "Vines");
		  ItemList.ID.put("107", "Fence Gate");
		  ItemList.ID.put("108", "Brick Stairs");
		  ItemList.ID.put("109", "Stone Brick Stairs");
		  ItemList.ID.put("110", "Mycelium");
		  ItemList.ID.put("111", "Lily Pad");
		  ItemList.ID.put("112", "Nether Brick");
		  ItemList.ID.put("113", "Nether Brick Fence");
		  ItemList.ID.put("114", "Nether Brick Stairs");
		  ItemList.ID.put("115", "Nether Wart");
		  ItemList.ID.put("116", "Enchantment Table");
		  ItemList.ID.put("117", "Brewing Stand (Block)");
		  ItemList.ID.put("118", "Cauldron (Block)");
		  ItemList.ID.put("119", "End Portal");
		  ItemList.ID.put("120", "End Portal Frame");
		  ItemList.ID.put("121", "End Stone");
		  ItemList.ID.put("122", "Dragon Egg");
		  ItemList.ID.put("256", "Iron Shovel");
		  ItemList.ID.put("257", "Iron Pickaxe");
		  ItemList.ID.put("258", "Iron Axe");
		  ItemList.ID.put("259", "Flint and Steel");
		  ItemList.ID.put("260", "Apple");
		  ItemList.ID.put("261", "Bow");
		  ItemList.ID.put("262", "Arrow");
		  ItemList.ID.put("263", "Coal");
		  ItemList.ID.put("263:1", "Charcoal");
		  ItemList.ID.put("264", "Diamond Gem");
		  ItemList.ID.put("265", "Iron Ingot");
		  ItemList.ID.put("266", "Gold Ingot");
		  ItemList.ID.put("267", "Iron Sword");
		  ItemList.ID.put("268", "Wooden Sword");
		  ItemList.ID.put("269", "Wooden Shovel");
		  ItemList.ID.put("270", "Wooden Pickaxe");
		  ItemList.ID.put("271", "Wooden Axe");
		  ItemList.ID.put("272", "Stone Sword");
		  ItemList.ID.put("273", "Stone Shovel");
		  ItemList.ID.put("274", "Stone Pickaxe");
		  ItemList.ID.put("275", "Stone Axe");
		  ItemList.ID.put("276", "Diamond Sword");
		  ItemList.ID.put("277", "Diamond Shovel");
		  ItemList.ID.put("278", "Diamond Pickaxe");
		  ItemList.ID.put("279", "Diamond Axe");
		  ItemList.ID.put("280", "Stick");
		  ItemList.ID.put("281", "Bowl");
		  ItemList.ID.put("282", "Mushroom Stew");
		  ItemList.ID.put("283", "Gold Sword");
		  ItemList.ID.put("284", "Gold Shovel");
		  ItemList.ID.put("285", "Gold Pickaxe");
		  ItemList.ID.put("286", "Gold Axe");
		  ItemList.ID.put("287", "String");
		  ItemList.ID.put("288", "Feather");
		  ItemList.ID.put("289", "Gunpowder");
		  ItemList.ID.put("290", "Wooden Hoe");
		  ItemList.ID.put("291", "Stone Hoe");
		  ItemList.ID.put("292", "Iron Hoe");
		  ItemList.ID.put("293", "Diamond Hoe");
		  ItemList.ID.put("294", "Gold Hoe");
		  ItemList.ID.put("295", "Wheat Seeds");
		  ItemList.ID.put("296", "Wheat");
		  ItemList.ID.put("297", "Bread");
		  ItemList.ID.put("298", "Leather Helmet");
		  ItemList.ID.put("299", "Leather Chestplate");
		  ItemList.ID.put("300", "Leather Leggings");
		  ItemList.ID.put("301", "Leather Boots");
		  ItemList.ID.put("302", "Chainmail Helmet");
		  ItemList.ID.put("303", "Chainmail Chestplate");
		  ItemList.ID.put("304", "Chainmail Leggings");
		  ItemList.ID.put("305", "Chainmail Boots");
		  ItemList.ID.put("306", "Iron Helmet");
		  ItemList.ID.put("307", "Iron Chestplate");
		  ItemList.ID.put("308", "Iron Leggings");
		  ItemList.ID.put("309", "Iron Boots");
		  ItemList.ID.put("310", "Diamond Helmet");
		  ItemList.ID.put("311", "Diamond Chestplate");
		  ItemList.ID.put("312", "Diamond Leggings");
		  ItemList.ID.put("313", "Diamond Boots");
		  ItemList.ID.put("314", "Gold Helmet");
		  ItemList.ID.put("315", "Gold Chestplate");
		  ItemList.ID.put("316", "Gold Leggings");
		  ItemList.ID.put("317", "Gold Boots");
		  ItemList.ID.put("318", "Flint");
		  ItemList.ID.put("319", "Raw Porkchop");
		  ItemList.ID.put("320", "Cooked Porkchop");
		  ItemList.ID.put("321", "Painting");
		  ItemList.ID.put("322", "Gold Apple");
		  ItemList.ID.put("323", "Sign");
		  ItemList.ID.put("324", "Wooden Door");
		  ItemList.ID.put("325", "Bucket");
		  ItemList.ID.put("326", "Bucket (Water)");
		  ItemList.ID.put("327", "Bucket (Lava)");
		  ItemList.ID.put("328", "Minecart");
		  ItemList.ID.put("329", "Saddle");
		  ItemList.ID.put("330", "Iron Door");
		  ItemList.ID.put("331", "Redstone Dust");
		  ItemList.ID.put("332", "Snowball");
		  ItemList.ID.put("333", "Boat");
		  ItemList.ID.put("334", "Leather");
		  ItemList.ID.put("335", "Bucket (Milk)");
		  ItemList.ID.put("336", "Clay Brick");
		  ItemList.ID.put("337", "Clay");
		  ItemList.ID.put("338", "Sugar Cane");
		  ItemList.ID.put("339", "Paper");
		  ItemList.ID.put("340", "Book");
		  ItemList.ID.put("341", "Slime Ball");
		  ItemList.ID.put("342", "Storage Minecart");
		  ItemList.ID.put("343", "Powered Minecart");
		  ItemList.ID.put("344", "Egg");
		  ItemList.ID.put("345", "Compass");
		  ItemList.ID.put("346", "Fishing Rod");
		  ItemList.ID.put("347", "Watch");
		  ItemList.ID.put("348", "Glowstone Dust");
		  ItemList.ID.put("349", "Raw Fish");
		  ItemList.ID.put("350", "Cooked Fish");
		  ItemList.ID.put("351", "Ink Sack");
		  ItemList.ID.put("351:1", "Rose Red Dye");
		  ItemList.ID.put("351:2", "Cactus Green Dye");
		  ItemList.ID.put("351:3", "Coca Bean");
		  ItemList.ID.put("351:4", "Lapis Lazuli");
		  ItemList.ID.put("351:5", "Purple Dye");
		  ItemList.ID.put("351:6", "Cyan Dye");
		  ItemList.ID.put("351:7", "Light Gray Dye");
		  ItemList.ID.put("351:8", "Gray Dye");
		  ItemList.ID.put("351:9", "Pink Dye");
		  ItemList.ID.put("351:10", "Lime Dye");
		  ItemList.ID.put("351:11", "Dandelion Yellow Dye");
		  ItemList.ID.put("351:12", "Light Blue Dye");
		  ItemList.ID.put("351:13", "Magenta Dye");
		  ItemList.ID.put("351:14", "Orange Dye");
		  ItemList.ID.put("351:15", "Bone Meal");
		  ItemList.ID.put("352", "Bone");
		  ItemList.ID.put("353", "Sugar");
		  ItemList.ID.put("354", "Cake");
		  ItemList.ID.put("355", "Bed");
		  ItemList.ID.put("356", "Redstone Repeater");
		  ItemList.ID.put("357", "Cookie");
		  ItemList.ID.put("358", "Map");
		  ItemList.ID.put("359", "Shears");
		  ItemList.ID.put("360", "Melon (Slice)");
		  ItemList.ID.put("361", "Pumpkin Seeds");
		  ItemList.ID.put("362", "Melon Seeds");
		  ItemList.ID.put("363", "Raw Beef");
		  ItemList.ID.put("364", "Steak");
		  ItemList.ID.put("365", "Raw Chicken");
		  ItemList.ID.put("366", "Cooked Chicken");
		  ItemList.ID.put("367", "Rotten Flesh");
		  ItemList.ID.put("368", "Ender Perl");
		  ItemList.ID.put("369", "Blaze Rod");
		  ItemList.ID.put("370", "Ghast Tear");
		  ItemList.ID.put("371", "Gold Nugget");
		  ItemList.ID.put("372", "Nether Wart Seeds");
		  ItemList.ID.put("373", "Water Bottle");
		  ItemList.ID.put("373:16", "Awkward Potion");
		  ItemList.ID.put("373:32", "Thick Potion");
		  ItemList.ID.put("373:64", "Mundane Potion");
		  ItemList.ID.put("373:8193", "Regeneration Potion");
		  ItemList.ID.put("373:8194", "Swiftness Potion");
		  ItemList.ID.put("373:8195", "Fire Resistance Potion");
		  ItemList.ID.put("373:8196", "Poison Potion");
		  ItemList.ID.put("373:8197", "Healing Potion");
		  ItemList.ID.put("373:8200", "Weakness Potion");
		  ItemList.ID.put("373:8201", "Strength Potion (3:00)");
		  ItemList.ID.put("373:8202", "Slowness Potion (1:30)");
		  ItemList.ID.put("373:8204", "Harming Potion");
		  ItemList.ID.put("373:8225", "Regeneration Potion II (0:22)");
		  ItemList.ID.put("373:8226", "Swiftness Potion II (1:30)");
		  ItemList.ID.put("373:8228", "Poison Potion II (0:22)");
		  ItemList.ID.put("373:8229", "Healing Potion II");
		  ItemList.ID.put("373:8233", "Strength Potion II (1:30)");
		  ItemList.ID.put("373:8236", "Harming Potion II");
		  ItemList.ID.put("373:8257", "Regeneration Potion (2:00)");
		  ItemList.ID.put("373:8258", "Swiftness Potion (8:00)");
		  ItemList.ID.put("373:8259", "Fire Resistance Potion (8:00)");
		  ItemList.ID.put("373:8260", "Poison Potion (2:00)");
		  ItemList.ID.put("373:8264", "Weakness Potion (4:00)");
		  ItemList.ID.put("373:8265", "Strength Potion (8:00)");
		  ItemList.ID.put("373:8266", "Slowness Potion (4:00)");
		  ItemList.ID.put("373:16378", "Fire Resistance Splash (2:15)");
		  ItemList.ID.put("373:16385", "Regeneration Splash (0:33)");
		  ItemList.ID.put("373:16386", "Swiftness Splash (2:15)");
		  ItemList.ID.put("373:16388", "Poison Splash (0:33)");
		  ItemList.ID.put("373:16389", "Healing Splash");
		  ItemList.ID.put("373:16392", "Weakness Splash (1:07)");
		  ItemList.ID.put("373:16393", "Strength Splash (2:15)");
		  ItemList.ID.put("373:16394", "Slowness Splash (1:07)");
		  ItemList.ID.put("373:16396", "Harming Splash");
		  ItemList.ID.put("373:16418", "Swiftness Splash II (1:07)");
		  ItemList.ID.put("373:16420", "Poison Splash II (0:16)");
		  ItemList.ID.put("373:16421", "Healing Splash II");
		  ItemList.ID.put("373:16425", "Strength Splash II (1:07)");
		  ItemList.ID.put("373:16428", "Harming Splash II");
		  ItemList.ID.put("373:16449", "Regeneration Splash (1:30)");
		  ItemList.ID.put("373:16450", "Swiftness Splash (6:00)");
		  ItemList.ID.put("373:16451", "Fire Resistance Splash (6:00)");
		  ItemList.ID.put("373:16452", "Poison Splash (1:30)");
		  ItemList.ID.put("373:16456", "Weakness Splash (3:00)");
		  ItemList.ID.put("373:16457", "Strength Splash (6:00)");
		  ItemList.ID.put("373:16458", "Slowness Splash (3:00)");
		  ItemList.ID.put("373:16471", "Regeneration Splash II (0:16)");
		  ItemList.ID.put("374", "Glass Bottle");
		  ItemList.ID.put("375", "Spider Eye");
		  ItemList.ID.put("376", "Fermented Spider Eye");
		  ItemList.ID.put("377", "Blaze Powder");
		  ItemList.ID.put("378", "Magma Cream");
		  ItemList.ID.put("379", "Brewing Stand");
		  ItemList.ID.put("380", "Cauldron");
		  ItemList.ID.put("381", "Eye of Ender");
		  ItemList.ID.put("382", "Glistering Melon (Slice)");
		  ItemList.ID.put("2256", "Music Disk (13)");
		  ItemList.ID.put("2257", "Music Disk (Cat)");
		  ItemList.ID.put("2258", "Music Disk (Blocks)");
		  ItemList.ID.put("2259", "Music Disk (Chirp)");
		  ItemList.ID.put("2260", "Music Disk (Far)");
		  ItemList.ID.put("2261", "Music Disk (Mall)");
		  ItemList.ID.put("2262", "Music Disk (Mellohi)");
		  ItemList.ID.put("2263", "Music Disk (Stal)");
		  ItemList.ID.put("2264", "Music Disk (Strad)");
		  ItemList.ID.put("2265", "Music Disk (Ward)");
		  ItemList.ID.put("2266", "Music Disk (11)");
	}
}
